networks:
  banco:
  web:
    name: web

services:
  db:
    image: postgres:17-alpine
    container_name: banco_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=America/Sao_Paulo
    ports:
      - "5435:5432"
    volumes:
      - "../.data/postgres:/var/lib/postgresql/data"
      - "./backups:/home/backups"
    networks:
      - banco
    restart: always
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teste_pratico_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - banco
      - web
    volumes:
      - .:/app
      - /app/target
    env_file:
      - .env

  # Frontend React
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: teste_pratico_frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
    depends_on:
      - backend
    networks:
      - web
    volumes:
      - ../frontend:/app
      - /app/node_modules

